export const users = [
  {
    id: 1,
    name: 'Hassan Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    number: '614363807',
    bagage: 'petit sac',
    depart: 'casablanca',
    arrive: 'mohammedia',
    prix: '200', 
    date: '03/06/2021',
    type_vehicule: 'clio 4',
    confort_voiture: 'bien',
    heureDepart: '10:15',
    heureArrivee: '12:20',
    rating:'3.5',
    
    nbr_place_dispo: '1',
    nom:'',
    prenom:'',
    jour:'',
    mois:'',
    annee:'',
    sexe:'',
    telephone:'',
    username1:'',
    password:'',
    ville:'',
    picture:''
  },
  {
    id: 2,
    name: 'Ervin',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    number:'614363807',
    depart:'meknes',
    rating:'4.5',
    type_vehicule:'dacia logan',
    confort_voiture:'parfait',
    nbr_place_dispo:'2',
    bagage:'petit sac',
    arrive:'fes',
    prix:'400',
    date:'03/07/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 3,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    number:'614363807',
    rating:'2.0',
    bagage:'petit sac',
    type_vehicule:'audi x5',
    confort_voiture:'pas mal',
    depart:'casablanca',
    nbr_place_dispo:'1',
    arrive:'fes',
    prix:'200',
    date:'03/08/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    number:'614363807',
    bagage:'grand sac',
    rating:'2.5',
    depart:'meknes',
    type_vehicule:'audi x5',
    confort_voiture:'pas mal',
    arrive:'fes',
    prix:'400',
    date:'03/06/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    number:'614363807',
    type_vehicule:'audi x5',
    confort_voiture:'pas mal',
    rating:'5.0',
    depart:'casablanca',
    bagage:'petit sac',
    arrive:'mohammedia',
    prix:'200',
    date:'03/06/2021',
    nbr_place_dispo:'1',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 6,
    name: 'Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    number:'614363807',
    depart:'casablanca',
    arrive:'mohammedia',
    type_vehicule:'audi x5',
    rating:'1.5',
    confort_voiture:'pas mal',
    bagage:'grand sac',
    nbr_place_dispo:'1',
    prix:'200',
    date:'03/10/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 7,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    nbr_place_dispo:'2',
    number:'614363807',
    type_vehicule:'audi x5',
    confort_voiture:'pas mal',
    bagage:'petit sac',
    depart:'meknes',
    arrive:'fes',
    prix:'400',
    date:'03/11/2021',
     heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    number:'614363807',
    rating:'3.5',
    type_vehicule:'audi x5',
    confort_voiture:'pas mal',
    depart:'casablanca',
    bagage:'grand sac',
    arrive:'mohammedia',
    prix:'200',
    date:'03/12/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    username: 'Delphine',
    type_vehicule:'audi x5',
    confort_voiture:'pas mal',
    nbr_place_dispo:'1',
    email: 'Chaim_McDermott@dana.io',
    number:'614363807',
    rating:'3.5',
    bagage:'petit sac',
    depart:'meknes',
    arrive:'fes',
    prix:'400',
    date:'03/13/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  },
  {
    id: 10,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    number:'614363807',
    bagage:'petit sac',
    type_vehicule:'audi x6',
    confort_voiture:'pas mal',
    depart:'casablanca',
    rating:'3.5',
    arrive:'mohammedia',
    prix:'200',
    nbr_place_dispo:'1',
    date:'03/14/2021',
    heureDepart:'10:15',
    heureArrivee:'12:20'
  }
];
